// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsFacilityManagementAPI.Data;

#nullable disable

namespace SportsFacilityManagementAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240625223259_UpdateDatabase")]
    partial class UpdateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SportsFacilityManagementAPI.Model.EspacioDeportivo", b =>
                {
                    b.Property<int>("EspaciosDeportivosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Locacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EspaciosDeportivosId");

                    b.ToTable("EspaciosDeportivos", (string)null);
                });

            modelBuilder.Entity("SportsFacilityManagementAPI.Model.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("EspacioDeportivoId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("EspacioDeportivoId");

                    b.ToTable("Reservaciones");
                });

            modelBuilder.Entity("SportsFacilityManagementAPI.Model.Reserva", b =>
                {
                    b.HasOne("SportsFacilityManagementAPI.Model.EspacioDeportivo", "espacioDeportivo")
                        .WithMany()
                        .HasForeignKey("EspacioDeportivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("espacioDeportivo");
                });
#pragma warning restore 612, 618
        }
    }
}
